#!/bin/bash

# Skill Sync - Sincroniza metadata de skills a AGENTS.md
# Usage: ./sync.sh [--dry-run] [--scope <scope>] [--verbose]

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKILLS_DIR="$(dirname "$(dirname "$SCRIPT_DIR")")"
PROJECT_ROOT="$(dirname "$SKILLS_DIR")"

# Defaults
DRY_RUN=false
VERBOSE=false
TARGET_SCOPE=""

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log() { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[OK]${NC} $1"; }
log_warning() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }
log_verbose() { [[ "$VERBOSE" == "true" ]] && echo -e "${BLUE}[DEBUG]${NC} $1"; }

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --dry-run)
            DRY_RUN=true
            shift
            ;;
        --verbose)
            VERBOSE=true
            shift
            ;;
        --scope)
            TARGET_SCOPE="$2"
            shift 2
            ;;
        --help|-h)
            echo "Usage: ./sync.sh [OPTIONS]"
            echo ""
            echo "Options:"
            echo "  --dry-run     Preview changes without writing"
            echo "  --scope NAME  Only sync specific scope (root, frontend, backend)"
            echo "  --verbose     Show detailed output"
            echo "  --help        Show this help"
            exit 0
            ;;
        *)
            log_error "Unknown option: $1"
            exit 1
            ;;
    esac
done

# Scope to file mapping
get_agents_file() {
    local scope=$1
    case $scope in
        root) echo "$PROJECT_ROOT/AGENTS.md" ;;
        frontend) echo "$PROJECT_ROOT/frontend/AGENTS.md" ;;
        backend) echo "$PROJECT_ROOT/backend/AGENTS.md" ;;
        *) echo "" ;;
    esac
}

# Extract YAML frontmatter value
extract_yaml_value() {
    local file=$1
    local key=$2
    # Simple extraction - works for basic cases
    sed -n '/^---$/,/^---$/p' "$file" | grep "^${key}:" | sed "s/${key}:[[:space:]]*//"
}

# Extract array values from YAML
extract_yaml_array() {
    local file=$1
    local key=$2
    sed -n '/^---$/,/^---$/p' "$file" | \
        sed -n "/^[[:space:]]*${key}:/,/^[[:space:]]*[a-z_]*:/p" | \
        grep '^\s*-' | \
        sed 's/^\s*-\s*//' | \
        sed 's/"//g' | \
        sed "s/'//g"
}

# Collect skills data
declare -A SKILLS_BY_SCOPE

collect_skills() {
    log "Scanning skills directory..."

    for skill_dir in "$SKILLS_DIR"/*/; do
        [[ -d "$skill_dir" ]] || continue
        [[ "$(basename "$skill_dir")" == "assets" ]] && continue

        local skill_file="$skill_dir/SKILL.md"
        [[ -f "$skill_file" ]] || continue

        local skill_name=$(basename "$skill_dir")
        log_verbose "Processing skill: $skill_name"

        # Extract scopes
        local scopes=$(extract_yaml_array "$skill_file" "scope")
        # Extract auto_invoke actions
        local actions=$(extract_yaml_array "$skill_file" "auto_invoke")

        # Add to each scope
        while IFS= read -r scope; do
            [[ -z "$scope" ]] && continue
            scope=$(echo "$scope" | tr -d '[],' | xargs)

            while IFS= read -r action; do
                [[ -z "$action" ]] && continue
                action=$(echo "$action" | xargs)

                # Append to scope array
                SKILLS_BY_SCOPE["$scope"]+="$action|$skill_name"$'\n'
                log_verbose "  Added: $action -> $skill_name (scope: $scope)"
            done <<< "$actions"
        done <<< "$scopes"
    done
}

# Generate markdown table for a scope
generate_table() {
    local scope=$1
    local data="${SKILLS_BY_SCOPE[$scope]}"

    echo "## Auto-invoke Skills"
    echo ""
    echo "<!-- This section is auto-generated by skill-sync. Do not edit manually. -->"
    echo ""
    echo "| Action | Skill |"
    echo "|--------|-------|"

    # Sort by action name and output
    echo "$data" | sort -t'|' -k1 | while IFS='|' read -r action skill; do
        [[ -z "$action" ]] && continue
        echo "| $action | $skill |"
    done
}

# Update AGENTS.md file
update_agents_file() {
    local scope=$1
    local agents_file=$(get_agents_file "$scope")

    [[ -z "$agents_file" ]] && return
    [[ ! -f "$agents_file" ]] && {
        log_warning "File not found: $agents_file"
        return
    }

    log "Updating $agents_file..."

    # Generate new table
    local new_table=$(generate_table "$scope")

    if [[ "$DRY_RUN" == "true" ]]; then
        log "  [DRY-RUN] Would update with:"
        echo "$new_table" | head -10
        echo "  ..."
        return
    fi

    # Create temp file
    local temp_file=$(mktemp)

    # Replace section between ## Auto-invoke Skills and next ##
    awk -v new_content="$new_table" '
        /^## Auto-invoke Skills/ {
            print new_content
            in_section = 1
            next
        }
        in_section && /^## / {
            in_section = 0
        }
        !in_section {
            print
        }
    ' "$agents_file" > "$temp_file"

    mv "$temp_file" "$agents_file"
    log_success "Updated $agents_file"
}

# Main
main() {
    log "Skill Sync starting..."
    [[ "$DRY_RUN" == "true" ]] && log_warning "DRY-RUN mode enabled"

    collect_skills

    # Determine which scopes to update
    local scopes=("root" "frontend" "backend")
    if [[ -n "$TARGET_SCOPE" ]]; then
        scopes=("$TARGET_SCOPE")
    fi

    for scope in "${scopes[@]}"; do
        if [[ -n "${SKILLS_BY_SCOPE[$scope]}" ]]; then
            update_agents_file "$scope"
        else
            log_verbose "No skills for scope: $scope"
        fi
    done

    log_success "Sync complete!"
}

main
