"""dashboard gestores cohorte cuatrimestre unidad avance

Revision ID: a1fc51f49e64
Revises: 012_add_gestor_rol
Create Date: 2026-06-03 17:07:53.320014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a1fc51f49e64'
down_revision: Union[str, None] = '012_add_gestor_rol'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cohortes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=False, comment="Código de la cohorte (ej: 'M25', 'A26')"),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cohortes'))
    )
    op.create_index(op.f('ix_cohortes_activa'), 'cohortes', ['activa'], unique=False)
    op.create_index(op.f('ix_cohortes_codigo'), 'cohortes', ['codigo'], unique=True)
    op.create_index(op.f('ix_cohortes_id'), 'cohortes', ['id'], unique=False)
    op.create_table('cuatrimestres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cohorte_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cohorte_id'], ['cohortes.id'], name=op.f('fk_cuatrimestres_cohorte_id_cohortes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cuatrimestres')),
    sa.UniqueConstraint('cohorte_id', 'numero', name='uq_cuatrimestre_cohorte_numero')
    )
    op.create_index(op.f('ix_cuatrimestres_cohorte_id'), 'cuatrimestres', ['cohorte_id'], unique=False)
    op.create_index(op.f('ix_cuatrimestres_id'), 'cuatrimestres', ['id'], unique=False)
    op.create_table('avance_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('materia_id', sa.Integer(), nullable=False),
    sa.Column('generado_en', sa.DateTime(), nullable=False),
    sa.Column('unidad_actual', sa.Integer(), nullable=True, comment='Valor de materia.unidad_actual CONGELADO al momento del snapshot'),
    sa.Column('origen', sa.Enum('CRON', 'MANUAL', name='origensnapshotenum'), nullable=False),
    sa.Column('total_alumnos', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], name=op.f('fk_avance_snapshots_materia_id_materias')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_avance_snapshots'))
    )
    op.create_index(op.f('ix_avance_snapshots_generado_en'), 'avance_snapshots', ['generado_en'], unique=False)
    op.create_index(op.f('ix_avance_snapshots_id'), 'avance_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_avance_snapshots_materia_id'), 'avance_snapshots', ['materia_id'], unique=False)
    op.create_table('unidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('materia_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False, comment='Número de unidad (1..N), define el orden'),
    sa.Column('moodle_section_id', sa.Integer(), nullable=False, comment="ID de la sección CABECERA de Moodle (la sección 'N- Tema')"),
    sa.Column('nombre', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], name=op.f('fk_unidades_materia_id_materias')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_unidades')),
    sa.UniqueConstraint('materia_id', 'moodle_section_id', name='uq_unidad_materia_section'),
    sa.UniqueConstraint('materia_id', 'numero', name='uq_unidad_materia_numero')
    )
    op.create_index(op.f('ix_unidades_id'), 'unidades', ['id'], unique=False)
    op.create_index(op.f('ix_unidades_materia_id'), 'unidades', ['materia_id'], unique=False)
    op.create_table('avance_alumnos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('moodle_user_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('apellido', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('comision', sa.String(length=50), nullable=True),
    sa.Column('unidad_alcanzada', sa.Integer(), nullable=True, comment='Unidad más alta completada; NULL si no completó ninguna'),
    sa.Column('actividad_actual_nombre', sa.String(length=255), nullable=True),
    sa.Column('actividad_actual_unidad', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Enum('AL_DIA', 'RIESGO_MEDIO', 'RIESGO_ALTO', 'SIN_ACTIVIDAD', name='estadoavanceenum'), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['avance_snapshots.id'], name=op.f('fk_avance_alumnos_snapshot_id_avance_snapshots')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_avance_alumnos'))
    )
    op.create_index(op.f('ix_avance_alumnos_estado'), 'avance_alumnos', ['estado'], unique=False)
    op.create_index(op.f('ix_avance_alumnos_id'), 'avance_alumnos', ['id'], unique=False)
    op.create_index(op.f('ix_avance_alumnos_moodle_user_id'), 'avance_alumnos', ['moodle_user_id'], unique=False)
    op.create_index(op.f('ix_avance_alumnos_snapshot_id'), 'avance_alumnos', ['snapshot_id'], unique=False)
    op.add_column('materias', sa.Column('cuatrimestre_id', sa.Integer(), nullable=True, comment='Cuatrimestre (y vía él, cohorte) al que pertenece la materia'))
    op.add_column('materias', sa.Column('unidad_actual', sa.Integer(), nullable=True, comment='Número de unidad que se está cursando (lo setea el admin)'))
    op.add_column('materias', sa.Column('moodle_section_fin_id', sa.Integer(), nullable=True, comment="ID de la 1ª sección de Moodle que YA NO es unidad de contenido (ej: 'Trabajo Integrador'). Actividades en secciones con section# >= el de ésta NO cuentan para el avance (parciales/integrador). NULL = sin tope."))
    op.create_index(op.f('ix_materias_cuatrimestre_id'), 'materias', ['cuatrimestre_id'], unique=False)
    op.create_foreign_key(op.f('fk_materias_cuatrimestre_id_cuatrimestres'), 'materias', 'cuatrimestres', ['cuatrimestre_id'], ['id'])
    op.add_column('rubricas', sa.Column('unidad_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_rubricas_unidad_id'), 'rubricas', ['unidad_id'], unique=False)
    op.create_foreign_key(op.f('fk_rubricas_unidad_id_unidades'), 'rubricas', 'unidades', ['unidad_id'], ['id'])
    # ### end Alembic commands ###

    # --- Seed idempotente de cohortes/cuatrimestres (PLAN_DASHBOARD_GESTORES.md §5.1) ---
    # M25: 4 cuatrimestres · A25: 2 · M26: 1 · A26: 1.
    op.execute(
        """
        INSERT INTO cohortes (codigo, activa, created_at, updated_at)
        VALUES
            ('M25', true, now(), now()),
            ('A25', true, now(), now()),
            ('M26', true, now(), now()),
            ('A26', true, now(), now())
        ON CONFLICT (codigo) DO NOTHING
        """
    )
    op.execute(
        """
        INSERT INTO cuatrimestres (cohorte_id, numero, created_at, updated_at)
        SELECT c.id, g.numero, now(), now()
        FROM cohortes c
        JOIN (VALUES
            ('M25', 1), ('M25', 2), ('M25', 3), ('M25', 4),
            ('A25', 1), ('A25', 2),
            ('M26', 1),
            ('A26', 1)
        ) AS g(codigo, numero) ON g.codigo = c.codigo
        ON CONFLICT (cohorte_id, numero) DO NOTHING
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_rubricas_unidad_id_unidades'), 'rubricas', type_='foreignkey')
    op.drop_index(op.f('ix_rubricas_unidad_id'), table_name='rubricas')
    op.drop_column('rubricas', 'unidad_id')
    op.drop_constraint(op.f('fk_materias_cuatrimestre_id_cuatrimestres'), 'materias', type_='foreignkey')
    op.drop_index(op.f('ix_materias_cuatrimestre_id'), table_name='materias')
    op.drop_column('materias', 'moodle_section_fin_id')
    op.drop_column('materias', 'unidad_actual')
    op.drop_column('materias', 'cuatrimestre_id')
    op.drop_index(op.f('ix_avance_alumnos_snapshot_id'), table_name='avance_alumnos')
    op.drop_index(op.f('ix_avance_alumnos_moodle_user_id'), table_name='avance_alumnos')
    op.drop_index(op.f('ix_avance_alumnos_id'), table_name='avance_alumnos')
    op.drop_index(op.f('ix_avance_alumnos_estado'), table_name='avance_alumnos')
    op.drop_table('avance_alumnos')
    op.drop_index(op.f('ix_unidades_materia_id'), table_name='unidades')
    op.drop_index(op.f('ix_unidades_id'), table_name='unidades')
    op.drop_table('unidades')
    op.drop_index(op.f('ix_avance_snapshots_materia_id'), table_name='avance_snapshots')
    op.drop_index(op.f('ix_avance_snapshots_id'), table_name='avance_snapshots')
    op.drop_index(op.f('ix_avance_snapshots_generado_en'), table_name='avance_snapshots')
    op.drop_table('avance_snapshots')
    op.drop_index(op.f('ix_cuatrimestres_id'), table_name='cuatrimestres')
    op.drop_index(op.f('ix_cuatrimestres_cohorte_id'), table_name='cuatrimestres')
    op.drop_table('cuatrimestres')
    op.drop_index(op.f('ix_cohortes_id'), table_name='cohortes')
    op.drop_index(op.f('ix_cohortes_codigo'), table_name='cohortes')
    op.drop_index(op.f('ix_cohortes_activa'), table_name='cohortes')
    op.drop_table('cohortes')
    # ### end Alembic commands ###
    # Los tipos enum nativos de PG no se eliminan al dropear la tabla → limpiarlos.
    op.execute("DROP TYPE IF EXISTS estadoavanceenum")
    op.execute("DROP TYPE IF EXISTS origensnapshotenum")
