"""notificaciones email

Revision ID: 42773c735505
Revises: 014_snapshot_cron_config
Create Date: 2026-06-07 12:17:39.307096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '42773c735505'
down_revision: Union[str, None] = '014_snapshot_cron_config'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('envio_email_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tanda_id', sa.String(length=64), nullable=False),
    sa.Column('tipo', sa.Enum('ALUMNO', 'TUTOR_ACADEMICO', 'TUTOR_NEXO', name='tiponotificacionenum'), nullable=False),
    sa.Column('destinatario_email', sa.String(length=150), nullable=False),
    sa.Column('destinatario_ref', sa.String(length=120), nullable=True),
    sa.Column('asunto', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.Enum('PENDIENTE', 'ENVIADO', 'ERROR', 'OMITIDO', name='estadoenvioenum'), nullable=False),
    sa.Column('resend_id', sa.String(length=120), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('intentos', sa.Integer(), server_default='0', nullable=False),
    sa.Column('enviado_en', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_envio_email_logs'))
    )
    op.create_index(op.f('ix_envio_email_logs_destinatario_email'), 'envio_email_logs', ['destinatario_email'], unique=False)
    op.create_index(op.f('ix_envio_email_logs_estado'), 'envio_email_logs', ['estado'], unique=False)
    op.create_index(op.f('ix_envio_email_logs_id'), 'envio_email_logs', ['id'], unique=False)
    op.create_index(op.f('ix_envio_email_logs_tanda_id'), 'envio_email_logs', ['tanda_id'], unique=False)
    op.create_index(op.f('ix_envio_email_logs_tipo'), 'envio_email_logs', ['tipo'], unique=False)
    op.create_table('tutores_nexo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('regional', sa.String(length=120), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tutores_nexo'))
    )
    op.create_index(op.f('ix_tutores_nexo_activo'), 'tutores_nexo', ['activo'], unique=False)
    op.create_index(op.f('ix_tutores_nexo_email'), 'tutores_nexo', ['email'], unique=False)
    op.create_index(op.f('ix_tutores_nexo_id'), 'tutores_nexo', ['id'], unique=False)
    op.create_index(op.f('ix_tutores_nexo_regional'), 'tutores_nexo', ['regional'], unique=False)
    op.create_table('notificacion_cron_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('dia_semana', sa.Integer(), server_default='0', nullable=False),
    sa.Column('hora', sa.Integer(), server_default='7', nullable=False),
    sa.Column('minuto', sa.Integer(), server_default='0', nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('remitente', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_notificacion_cron_config_usuario_id_usuarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notificacion_cron_config'))
    )
    op.add_column('avance_alumnos', sa.Column('regional', sa.String(length=120), nullable=True))
    op.add_column('avance_alumnos', sa.Column('actividades_faltantes', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_avance_alumnos_regional'), 'avance_alumnos', ['regional'], unique=False)
    op.add_column('usuarios', sa.Column('email', sa.String(length=150), nullable=True))
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_column('usuarios', 'email')
    op.drop_index(op.f('ix_avance_alumnos_regional'), table_name='avance_alumnos')
    op.drop_column('avance_alumnos', 'actividades_faltantes')
    op.drop_column('avance_alumnos', 'regional')
    op.drop_table('notificacion_cron_config')
    op.drop_index(op.f('ix_tutores_nexo_regional'), table_name='tutores_nexo')
    op.drop_index(op.f('ix_tutores_nexo_id'), table_name='tutores_nexo')
    op.drop_index(op.f('ix_tutores_nexo_email'), table_name='tutores_nexo')
    op.drop_index(op.f('ix_tutores_nexo_activo'), table_name='tutores_nexo')
    op.drop_table('tutores_nexo')
    op.drop_index(op.f('ix_envio_email_logs_tipo'), table_name='envio_email_logs')
    op.drop_index(op.f('ix_envio_email_logs_tanda_id'), table_name='envio_email_logs')
    op.drop_index(op.f('ix_envio_email_logs_id'), table_name='envio_email_logs')
    op.drop_index(op.f('ix_envio_email_logs_estado'), table_name='envio_email_logs')
    op.drop_index(op.f('ix_envio_email_logs_destinatario_email'), table_name='envio_email_logs')
    op.drop_table('envio_email_logs')
    # ### end Alembic commands ###
