"""unidad tp autoeval cierre cmids

Revision ID: 23e454a59b3f
Revises: 42773c735505
Create Date: 2026-06-07 16:26:40.536793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '23e454a59b3f'
down_revision: Union[str, None] = '42773c735505'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unidades', sa.Column('moodle_tp_cmid', sa.Integer(), nullable=True, comment='cmid del TP/entregable (assign) de la unidad'))
    op.add_column('unidades', sa.Column('moodle_autoeval_cmid', sa.Integer(), nullable=True, comment='cmid de la autoevaluación (quiz) de la unidad'))
    op.add_column('unidades', sa.Column('moodle_cierre_cmid', sa.Integer(), nullable=True, comment='cmid de la actividad de cierre (feedback) de la unidad'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('unidades', 'moodle_cierre_cmid')
    op.drop_column('unidades', 'moodle_autoeval_cmid')
    op.drop_column('unidades', 'moodle_tp_cmid')
    # ### end Alembic commands ###
