"""add moodle fields to usuario, materia, rubrica, comision

Revision ID: 4a01eb61e749
Revises: 009_add_correction_provider
Create Date: 2026-05-07 18:12:47.141902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a01eb61e749'
down_revision: Union[str, None] = '009_add_correction_provider'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comisiones', sa.Column('moodle_group_id', sa.Integer(), nullable=True))
    op.add_column('comisiones', sa.Column('moodle_group_code', sa.String(length=50), nullable=True))
    op.add_column('materias', sa.Column('moodle_course_id', sa.Integer(), nullable=True))
    op.add_column('rubricas', sa.Column('moodle_assign_id', sa.Integer(), nullable=True))
    op.add_column('usuarios', sa.Column('moodle_username', sa.String(length=100), nullable=True))
    op.add_column('usuarios', sa.Column('moodle_password_encrypted', sa.Text(), nullable=True))
    op.add_column('usuarios', sa.Column('moodle_host', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'moodle_host')
    op.drop_column('usuarios', 'moodle_password_encrypted')
    op.drop_column('usuarios', 'moodle_username')
    op.drop_column('rubricas', 'moodle_assign_id')
    op.drop_column('materias', 'moodle_course_id')
    op.drop_column('comisiones', 'moodle_group_code')
    op.drop_column('comisiones', 'moodle_group_id')
    # ### end Alembic commands ###
