# Pydantic Schemas
"""
Schemas package - Pydantic models for request/response validation.
"""

from app.schemas.auth import (
    ChangePasswordRequest,
    ChangePasswordResponse,
    LoginRequest,
    TokenResponse,
    UserInfo,
)
from app.schemas.comision import (
    ComisionCreate,
    ComisionDetailResponse,
    ComisionList,
    ComisionListItem,
    ComisionResponse,
    ComisionUpdate,
    MateriaInfo,
    TutorInfo,
    TutoresAssign,
    TutoresResponse,
)
from app.schemas.correccion import (
    CorreccionCreate,
    CorreccionListItem,
    CorreccionResponse,
    CorreccionUpdate,
    CorregirLoteRequest,
    CorregirLoteResponse,
    CriterioEvaluado,
    CriterioGeminiSchema,
    GeminiResponse,
)
from app.schemas.entrega import (
    CargaMasivaCreate,
    CargaMasivaResponse,
    ContenidoEntrega,
    EntregaCreate,
    EntregaCreada,
    EntregaDetailResponse,
    EntregaError,
    EntregaList,
    EntregaListItem,
    EntregaResponse,
    EntregaUpdate,
    HistorialItem,
    HistorialResponse,
)
from app.schemas.materia import (
    CoordinadorInfo,
    CoordinadoresAssign,
    CoordinadoresResponse,
    MateriaCreate,
    MateriaDetailResponse,
    MateriaList,
    MateriaListItem,
    MateriaResponse,
    MateriaUpdate,
)
from app.schemas.rubrica import (
    CriterioBase,
    CriteriosStructure,
    NivelDesempeno,
    RubricaCreate,
    RubricaDetailResponse,
    RubricaDuplicar,
    RubricaList,
    RubricaListItem,
    RubricaResponse,
    RubricaUpdate,
)
from app.schemas.usuario import (
    ResetPasswordResponse,
    UsuarioCreate,
    UsuarioCreateResponse,
    UsuarioList,
    UsuarioListItem,
    UsuarioResponse,
    UsuarioUpdate,
)

__all__ = [
    # Auth
    "LoginRequest",
    "TokenResponse",
    "UserInfo",
    "ChangePasswordRequest",
    "ChangePasswordResponse",
    # Usuario
    "UsuarioCreate",
    "UsuarioUpdate",
    "UsuarioResponse",
    "UsuarioListItem",
    "UsuarioList",
    "UsuarioCreateResponse",
    "ResetPasswordResponse",
    # Materia
    "MateriaCreate",
    "MateriaUpdate",
    "MateriaResponse",
    "MateriaDetailResponse",
    "MateriaListItem",
    "MateriaList",
    "CoordinadorInfo",
    "CoordinadoresAssign",
    "CoordinadoresResponse",
    # Comision
    "ComisionCreate",
    "ComisionUpdate",
    "ComisionResponse",
    "ComisionDetailResponse",
    "ComisionListItem",
    "ComisionList",
    "MateriaInfo",
    "TutorInfo",
    "TutoresAssign",
    "TutoresResponse",
    # Rubrica
    "NivelDesempeno",
    "CriterioBase",
    "CriteriosStructure",
    "RubricaCreate",
    "RubricaUpdate",
    "RubricaResponse",
    "RubricaDetailResponse",
    "RubricaListItem",
    "RubricaList",
    "RubricaDuplicar",
    # Entrega
    "EntregaCreate",
    "EntregaUpdate",
    "EntregaResponse",
    "EntregaDetailResponse",
    "EntregaListItem",
    "EntregaList",
    "CargaMasivaCreate",
    "CargaMasivaResponse",
    "EntregaCreada",
    "EntregaError",
    "ContenidoEntrega",
    "HistorialItem",
    "HistorialResponse",
    # Correccion
    "CriterioEvaluado",
    "CriterioGeminiSchema",
    "GeminiResponse",
    "CorreccionCreate",
    "CorreccionUpdate",
    "CorreccionResponse",
    "CorreccionListItem",
    "CorregirLoteRequest",
    "CorregirLoteResponse",
]
