# app/schemas/usuario.py
"""
Usuario schemas for Active-IA.

Pydantic models for user request/response validation.

Ref: docs/specs/03-REQUISITOS-FUNCIONALES.md seccion 3
Ref: docs/specs/06-MODELO-DATOS.md seccion 3.1
"""

from datetime import datetime

from pydantic import BaseModel, Field, field_validator

from app.models.enums import RolEnum


class UsuarioBase(BaseModel):
    """Base schema with common user fields."""

    username: str = Field(
        ...,
        min_length=3,
        max_length=50,
        pattern=r"^[a-zA-Z0-9_-]+$",
        description="Nombre de usuario (solo letras, números, guiones)",
        examples=["jperez"],
    )
    nombre: str = Field(
        ...,
        min_length=2,
        max_length=100,
        description="Nombre completo del usuario",
        examples=["Juan Pérez"],
    )
    rol: RolEnum = Field(
        ...,
        description="Rol del usuario en el sistema",
    )
    email: str | None = Field(
        None,
        max_length=150,
        description="Email del usuario (lo usa la notificación al tutor académico)",
        examples=["jperez@active-ia.com"],
    )

    @field_validator("username")
    @classmethod
    def _username_a_minuscula(cls, v: str) -> str:
        # CRUD-009: canonicalizar. Sin esto, exists_username(data.username) chequea
        # el valor crudo pero el insert guarda .lower() -> "JPerez" pasa el chequeo
        # (no existe "JPerez") y revienta contra el unique al guardar "jperez".
        return v.lower()


class UsuarioCreate(UsuarioBase):
    """Schema for creating a new user.

    Note: Password is auto-generated by the system.
    Admin receives the temporary password to communicate to the user.
    """

    pass


class UsuarioUpdate(BaseModel):
    """Schema for updating an existing user.

    All fields are optional - only provided fields will be updated.
    """

    nombre: str | None = Field(
        None,
        min_length=2,
        max_length=100,
        description="Nombre completo del usuario",
    )
    rol: RolEnum | None = Field(
        None,
        description="Nuevo rol del usuario",
    )
    email: str | None = Field(
        None,
        max_length=150,
        description="Email del usuario (notificaciones)",
    )


class UsuarioResponse(BaseModel):
    """Schema for user response (single user)."""

    id: int
    username: str
    nombre: str
    rol: RolEnum
    email: str | None = None
    primer_login: bool = Field(
        description="True si el usuario debe cambiar su contraseña",
    )
    gemini_api_key_valid: bool = Field(
        description="True si tiene API Key de Gemini configurada y validada",
    )
    moodle_configured: bool = Field(
        default=False,
        description="True si tiene credenciales Moodle configuradas",
    )
    activo: bool = Field(
        description="False si el usuario fue eliminado (soft delete)",
    )
    created_at: datetime
    updated_at: datetime
    last_login: datetime | None = Field(
        None,
        description="Fecha del último inicio de sesión",
    )

    model_config = {"from_attributes": True}


class UsuarioListItem(BaseModel):
    """Schema for user in a list (reduced fields)."""

    id: int
    username: str
    nombre: str
    rol: RolEnum
    activo: bool
    created_at: datetime
    last_login: datetime | None = None

    model_config = {"from_attributes": True}


class UsuarioList(BaseModel):
    """Schema for paginated list of users."""

    items: list[UsuarioListItem]
    total: int = Field(
        description="Total number of users matching the filter",
    )
    page: int = Field(
        default=1,
        ge=1,
        description="Current page number",
    )
    per_page: int = Field(
        default=20,
        ge=1,
        le=1000,
        description="Items per page",
    )


class UsuarioCreateResponse(BaseModel):
    """Response after creating a user (includes temp password)."""

    usuario: UsuarioResponse
    password_temporal: str = Field(
        description="Contraseña temporal generada (comunicar al usuario)",
    )


class ResetPasswordResponse(BaseModel):
    """Response after resetting a user's password."""

    message: str = Field(
        default="Contraseña reseteada exitosamente",
    )
    password_temporal: str = Field(
        description="Nueva contraseña temporal",
    )


class MoodleCredentialsUpdate(BaseModel):
    """Schema for updating Moodle credentials."""

    moodle_host: str = Field(
        ...,
        min_length=1,
        max_length=255,
        description="URL base del host Moodle (ej: https://moodle.ejemplo.com)",
        examples=["https://tup.sied.utn.edu.ar"],
    )
    moodle_username: str = Field(
        ...,
        min_length=1,
        max_length=100,
        description="Nombre de usuario en Moodle",
    )
    moodle_password: str = Field(
        ...,
        min_length=1,
        description="Contraseña en Moodle (se cifra con AES-256)",
    )


class MoodleCredentialsResponse(BaseModel):
    """Response after updating Moodle credentials."""

    moodle_username: str
    moodle_host: str
    configured: bool = True
