export {
  useRubricas,
  useAllRubricas,
  useRubrica,
  useCreateRubrica,
  useUpdateRubrica,
  useDeleteRubrica,
  useRestoreRubrica,
  useDuplicarRubrica,
  useGenerarRubricaDesdePDF,
  useDownloadRubricaPDF,
  useDownloadRubricaPDFResumido,
  usePreviewRubricaPDF,
  usePreviewRubricaPDFResumido,
} from './useRubricas';
